const PLANT_COLORS = {
  "梅花": "#c94f6b",
  "桃花": "#d7798f",
  "玉兰": "#b8873d",
  "樱花": "#d891aa",
  "海棠": "#c9635f",
  "二月兰": "#7d78bf",
  "牡丹": "#a84b86",
  "荷花": "#bd5d93",
  "月季": "#b95751",
  "油菜花": "#c7a12c",
  "丁香": "#8b76b6",
  "粉黛乱子草": "#bf82a2",
  "银杏": "#a98e36",
  "蜡梅": "#c9942e",
  "迎春": "#e3b82e",
  "连翘": "#d9a520",
  "榆叶梅": "#e8788a",
  "碧桃": "#d9607a",
  "郁金香": "#e0555a",
  "芍药": "#e88db0",
  "紫藤": "#8b7bb8",
  "向日葵": "#e8b830",
  "菊花": "#d4823a"
};

const PLANT_IMAGES = {
  "梅花": "./assets/plants/plum.png?v=20260427alpha",
  "桃花": "./assets/plants/peach.png?v=20260427alpha",
  "玉兰": "./assets/plants/magnolia.png?v=20260427alpha",
  "樱花": "./assets/plants/cherry.png?v=20260427alpha",
  "海棠": "./assets/plants/crabapple.png?v=20260427alpha",
  "二月兰": "./assets/plants/february-orchid.png?v=20260427alpha",
  "牡丹": "./assets/plants/peony.png?v=20260427alpha",
  "荷花": "./assets/plants/lotus.png?v=20260427alpha",
  "月季": "./assets/plants/rose.png?v=20260427alpha",
  "油菜花": "./assets/plants/rapeseed.png?v=20260427alpha",
  "丁香": "./assets/plants/lilac.png?v=20260427alpha",
  "粉黛乱子草": "./assets/plants/muhly-grass.png?v=20260427alpha",
  "银杏": "./assets/plants/ginkgo.png?v=20260427alpha",
  "蜡梅": "./assets/plants/wintersweet.png?v=20260428a",
  "迎春": "./assets/plants/winter-jasmine.png?v=20260428a",
  "连翘": "./assets/plants/forsythia.png?v=20260428a",
  "榆叶梅": "./assets/plants/flowering-almond.png?v=20260428a",
  "碧桃": "./assets/plants/flowering-peach.png?v=20260428a",
  "郁金香": "./assets/plants/tulip.png?v=20260428a",
  "芍药": "./assets/plants/peony-herbaceous.png?v=20260428a",
  "紫藤": "./assets/plants/wisteria.png?v=20260428a",
  "向日葵": "./assets/plants/sunflower.png?v=20260428a",
  "菊花": "./assets/plants/chrysanthemum.png?v=20260428a"
};

const MONTHLY_WIND_MODEL = {
  1: { direction: 330, speed: 3.4, label: "西北风" },
  2: { direction: 320, speed: 3.2, label: "西北风" },
  3: { direction: 300, speed: 3.5, label: "西北风" },
  4: { direction: 260, speed: 3.1, label: "西风" },
  5: { direction: 210, speed: 2.8, label: "西南风" },
  6: { direction: 170, speed: 2.5, label: "南风" },
  7: { direction: 150, speed: 2.4, label: "东南风" },
  8: { direction: 140, speed: 2.3, label: "东南风" },
  9: { direction: 210, speed: 2.5, label: "西南风" },
  10: { direction: 300, speed: 2.9, label: "西北风" },
  11: { direction: 330, speed: 3.2, label: "西北风" },
  12: { direction: 340, speed: 3.5, label: "西北风" }
};

const POLLEN_PROFILE = {
  "梅花": 0.35,
  "桃花": 0.6,
  "玉兰": 0.38,
  "樱花": 0.55,
  "海棠": 0.58,
  "二月兰": 0.42,
  "牡丹": 0.32,
  "荷花": 0.2,
  "月季": 0.48,
  "油菜花": 0.72,
  "丁香": 0.42,
  "粉黛乱子草": 0.68,
  "银杏": 0.8,
  "蜡梅": 0.25,
  "迎春": 0.35,
  "连翘": 0.40,
  "榆叶梅": 0.50,
  "碧桃": 0.55,
  "郁金香": 0.25,
  "芍药": 0.30,
  "紫藤": 0.35,
  "向日葵": 0.60,
  "菊花": 0.45
};

const ALLERGY_PROFILE = {
  "梅花": 1,
  "桃花": 1,
  "玉兰": 1,
  "樱花": 1,
  "海棠": 1,
  "二月兰": 2,
  "牡丹": 1,
  "荷花": 1,
  "月季": 1,
  "油菜花": 2,
  "丁香": 2,
  "粉黛乱子草": 3,
  "银杏": 3,
  "蜡梅": 1,
  "迎春": 2,
  "连翘": 2,
  "榆叶梅": 1,
  "碧桃": 1,
  "郁金香": 1,
  "芍药": 1,
  "紫藤": 1,
  "向日葵": 2,
  "菊花": 2
};

const DISTRICTS = [
  { name: "海淀", lat: 39.96, lng: 116.30 },
  { name: "朝阳", lat: 39.94, lng: 116.55 },
  { name: "西城", lat: 39.91, lng: 116.37 },
  { name: "东城", lat: 39.93, lng: 116.42 },
  { name: "丰台", lat: 39.84, lng: 116.29 },
  { name: "石景山", lat: 39.91, lng: 116.19 },
  { name: "通州", lat: 39.90, lng: 116.72 },
  { name: "昌平", lat: 40.22, lng: 116.23 },
  { name: "顺义", lat: 40.13, lng: 116.65 },
  { name: "大兴", lat: 39.73, lng: 116.34 },
  { name: "门头沟", lat: 39.94, lng: 115.98 },
  { name: "怀柔", lat: 40.32, lng: 116.63 },
  { name: "密云", lat: 40.38, lng: 116.84 },
  { name: "延庆", lat: 40.46, lng: 115.98 },
  { name: "房山", lat: 39.74, lng: 116.13 },
  { name: "平谷", lat: 40.14, lng: 117.12 }
];

const PLANT_SPOTS = [
  {
    id: "ming-wall-plum",
    district: "东城区",
    place: "北京明城墙遗址公园",
    plant: "梅花",
    bloom: "3月中旬至4月上旬",
    months: [3, 4],
    peak: 3,
    area: 3000,
    countText: "50余个品种千余株",
    lat: 39.899,
    lng: 116.429,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "以梅花为重点花卉，设置西劳模广场、角楼下、信号所西等观赏节点。"
  },
  {
    id: "side-park-plum",
    district: "朝阳区",
    place: "四得公园",
    plant: "梅花",
    bloom: "2月至3月",
    months: [2, 3],
    peak: 3,
    area: 170000,
    countText: "251株",
    lat: 39.972,
    lng: 116.489,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "早春梅花点位，适合与朝阳区其他春花点位串联。"
  },
  {
    id: "yuanmingyuan-plum",
    district: "海淀区",
    place: "圆明园遗址公园",
    plant: "梅花",
    bloom: "3月至4月",
    months: [3, 4],
    peak: 3,
    area: 5000,
    countText: "廓然大公区域",
    lat: 40.008,
    lng: 116.303,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "梅花主要在廓然大公区域形成观赏效果。"
  },
  {
    id: "aosen-peach",
    district: "朝阳区",
    place: "奥林匹克森林公园",
    plant: "桃花",
    bloom: "3月中旬至3月底",
    months: [3],
    peak: 3,
    area: 80000,
    countText: "山桃4500株",
    lat: 40.016,
    lng: 116.393,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "山桃集中成景，是北京早春最醒目的粉色花带之一。"
  },
  {
    id: "tuanjiehu-peach",
    district: "朝阳区",
    place: "团结湖公园",
    plant: "桃花",
    bloom: "3月至4月",
    months: [3, 4],
    peak: 4,
    area: 123000,
    countText: "碧桃749株",
    lat: 39.934,
    lng: 116.463,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "以碧桃为主要春季观赏花木。"
  },
  {
    id: "yuanmingyuan-peach",
    district: "海淀区",
    place: "圆明园遗址公园",
    plant: "桃花",
    bloom: "3月中旬至5月上旬",
    months: [3, 4, 5],
    peak: 4,
    area: 40000,
    countText: "武陵春色区域",
    lat: 40.012,
    lng: 116.304,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "山桃、碧桃分布较多，以武陵春色区域观赏效果最佳。"
  },
  {
    id: "longtan-magnolia",
    district: "东城区",
    place: "龙潭公园",
    plant: "玉兰",
    bloom: "3月上旬至5月下旬",
    months: [3, 4, 5],
    peak: 4,
    area: 4000,
    countText: "主路沿线及景观节点",
    lat: 39.878,
    lng: 116.435,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "玉兰与樱花、海棠、碧桃等春花共同形成集中赏花片区。"
  },
  {
    id: "ritan-magnolia",
    district: "朝阳区",
    place: "日坛公园",
    plant: "玉兰",
    bloom: "3月至4月",
    months: [3, 4],
    peak: 3,
    area: 198000,
    countText: "149棵",
    lat: 39.915,
    lng: 116.444,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "市中心可达性较好的玉兰观赏点。"
  },
  {
    id: "yuanmingyuan-magnolia",
    district: "海淀区",
    place: "圆明园遗址公园",
    plant: "玉兰",
    bloom: "3月至4月",
    months: [3, 4],
    peak: 4,
    area: 5000,
    countText: "玉兰堂、含经堂等区域",
    lat: 40.014,
    lng: 116.306,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "园区内分布较多，玉兰堂、滴远、含经堂、九州清晏观赏效果较好。"
  },
  {
    id: "guanyuan-sakura",
    district: "西城区",
    place: "官园公园",
    plant: "樱花",
    bloom: "4月至5月",
    months: [4, 5],
    peak: 4,
    area: 10000,
    countText: "樱花",
    lat: 39.932,
    lng: 116.356,
    source: "北京市园林绿化局 2026年樱花赏花指南",
    description: "西城区樱花点位，花期集中在4月至5月。"
  },
  {
    id: "beixiaohe-sakura",
    district: "朝阳区",
    place: "北小河公园",
    plant: "樱花",
    bloom: "3月至4月",
    months: [3, 4],
    peak: 4,
    area: 195900,
    countText: "1198株",
    lat: 40.023,
    lng: 116.476,
    source: "北京市园林绿化局 2026年樱花赏花指南",
    description: "朝阳区大型樱花点位，数量较多，适合做春季热点。"
  },
  {
    id: "chaoyang-park-sakura",
    district: "朝阳区",
    place: "朝阳公园",
    plant: "樱花",
    bloom: "4月",
    months: [4],
    peak: 4,
    area: 2887000,
    countText: "410株/10000平米",
    lat: 39.946,
    lng: 116.484,
    source: "北京市园林绿化局 2026年樱花赏花指南",
    description: "朝阳公园春季樱花点位，适合与海棠、月季等公园资源叠加展示。"
  },
  {
    id: "duzhong-sakura",
    district: "朝阳区",
    place: "杜仲公园",
    plant: "樱花",
    bloom: "4月至5月",
    months: [4, 5],
    peak: 4,
    area: 599000,
    countText: "1093株/8000平米",
    lat: 39.884,
    lng: 116.526,
    source: "北京市园林绿化局 2026年樱花赏花指南",
    description: "朝阳东南方向的樱花观赏点，适合补足城市东部花期分布。"
  },
  {
    id: "yuandadu-crabapple",
    district: "朝阳区",
    place: "元大都城垣遗址公园（朝阳段）",
    plant: "海棠",
    bloom: "4月",
    months: [4],
    peak: 4,
    area: 670000,
    countText: "10000余株，35000余平方米",
    lat: 39.976,
    lng: 116.414,
    source: "北京市园林绿化局 2026年海棠赏花指南",
    description: "元大都海棠花溪是北京春季海棠代表性片区。"
  },
  {
    id: "wenyu-crabapple",
    district: "朝阳区",
    place: "温榆河公园（朝阳）",
    plant: "海棠",
    bloom: "4月至5月",
    months: [4, 5],
    peak: 4,
    area: 1249300,
    countText: "55000平方米",
    lat: 40.085,
    lng: 116.579,
    source: "北京市园林绿化局 2026年海棠赏花指南",
    description: "北部大型公园海棠片区，可与油菜花点位共同展示。"
  },
  {
    id: "yuanmingyuan-crabapple",
    district: "海淀区",
    place: "圆明园遗址公园",
    plant: "海棠",
    bloom: "4月上旬",
    months: [4],
    peak: 4,
    area: 9000,
    countText: "含经堂、长春仙馆区域",
    lat: 40.011,
    lng: 116.309,
    source: "北京市园林绿化局 2026年海棠赏花指南",
    description: "西府海棠与古典园林空间结合，适合作为文化景观点。"
  },
  {
    id: "jiangfu-violet",
    district: "朝阳区",
    place: "将府郊野公园（一至三期）",
    plant: "二月兰",
    bloom: "3月至5月",
    months: [3, 4, 5],
    peak: 4,
    area: 2150000,
    countText: "730000平方米",
    lat: 39.987,
    lng: 116.537,
    source: "北京市园林绿化局 2026年二月兰赏花指南",
    description: "大面积地被花海，是二月兰分布展示的重点样本。"
  },
  {
    id: "jingchenghuai-violet",
    district: "朝阳区",
    place: "京城槐园",
    plant: "二月兰",
    bloom: "3月至4月",
    months: [3, 4],
    peak: 4,
    area: 651200,
    countText: "360000平米",
    lat: 39.951,
    lng: 116.556,
    source: "北京市园林绿化局 2026年二月兰赏花指南",
    description: "二月兰成片分布，适合表现地被植物的春季面状景观。"
  },
  {
    id: "yuanmingyuan-violet",
    district: "海淀区",
    place: "圆明园遗址公园",
    plant: "二月兰",
    bloom: "3月下旬至5月下旬",
    months: [3, 4, 5],
    peak: 4,
    area: 30000,
    countText: "月地云居、映水兰香、福海周边",
    lat: 40.009,
    lng: 116.311,
    source: "北京市园林绿化局 2026年二月兰赏花指南",
    description: "全园均有分布，其中月地云居、映水兰香、福海周边观赏效果较佳。"
  },
  {
    id: "ditan-peony",
    district: "东城区",
    place: "地坛公园",
    plant: "牡丹",
    bloom: "4月上旬至5月下旬",
    months: [4, 5],
    peak: 4,
    area: 2100,
    countText: "养生园周边",
    lat: 39.953,
    lng: 116.417,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "牡丹和芍药为主，搭配玉兰、碧桃、榆叶梅、丁香等花灌木。"
  },
  {
    id: "taiyanggong-peony",
    district: "朝阳区",
    place: "太阳宫公园",
    plant: "牡丹",
    bloom: "4月至5月",
    months: [4, 5],
    peak: 4,
    area: 321800,
    countText: "5万株/40000平米",
    lat: 39.972,
    lng: 116.456,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "数量和面积都较突出的牡丹点位。"
  },
  {
    id: "yuanmingyuan-peony",
    district: "海淀区",
    place: "圆明园遗址公园",
    plant: "牡丹",
    bloom: "4月中旬至5月上旬",
    months: [4, 5],
    peak: 4,
    area: 10000,
    countText: "近百种牡丹品种",
    lat: 40.013,
    lng: 116.313,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "镂月开云、含经堂、藻园门区域观赏效果较好。"
  },
  {
    id: "honglingjin-lotus",
    district: "朝阳区",
    place: "红领巾公园",
    plant: "荷花",
    bloom: "6月至8月",
    months: [6, 7, 8],
    peak: 7,
    area: 419900,
    countText: "63000株/18000平方米",
    lat: 39.928,
    lng: 116.493,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "夏季水生花卉代表点位，适合在时间轴中从春花过渡到夏花。"
  },
  {
    id: "lianhuachi-lotus",
    district: "丰台区",
    place: "莲花池公园",
    plant: "荷花",
    bloom: "6月至8月",
    months: [6, 7, 8],
    peak: 7,
    area: 446100,
    countText: "荷花、牡丹、芍药等",
    lat: 39.894,
    lng: 116.309,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "兼具春季牡丹芍药和夏季荷花的复合型点位。"
  },
  {
    id: "dawangjing-rose",
    district: "朝阳区",
    place: "大望京公园",
    plant: "月季",
    bloom: "5月至10月",
    months: [5, 6, 7, 8, 9, 10],
    peak: 5,
    area: 382700,
    countText: "49527株/8254平米",
    lat: 40.003,
    lng: 116.486,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "月季花期长，适合表现从初夏到秋季的持续观赏。"
  },
  {
    id: "rose-park-rose",
    district: "西城区",
    place: "玫瑰公园",
    plant: "月季",
    bloom: "4月底至5月下旬",
    months: [5],
    peak: 5,
    area: 2000,
    countText: "花色丰富",
    lat: 39.892,
    lng: 116.365,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "小而明确的月季观赏点，适合做中心城区补点。"
  },
  {
    id: "wenyu-rapeseed",
    district: "朝阳区",
    place: "温榆河公园（朝阳）",
    plant: "油菜花",
    bloom: "4月至5月",
    months: [4, 5],
    peak: 4,
    area: 49950,
    countText: "990000株/49950平方米",
    lat: 40.086,
    lng: 116.585,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "大面积黄色花田，适合增强地图色彩层次。"
  },
  {
    id: "liangshan-rapeseed",
    district: "海淀区",
    place: "两山公园",
    plant: "油菜花",
    bloom: "4月至5月",
    months: [4, 5],
    peak: 4,
    area: 55855,
    countText: "规模较大",
    lat: 40.055,
    lng: 116.173,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "海淀西部油菜花点位，可补充城区西北方向分布。"
  },
  {
    id: "qingfeng-lilac",
    district: "朝阳区",
    place: "庆丰公园",
    plant: "丁香",
    bloom: "4月至5月",
    months: [4, 5],
    peak: 4,
    area: 267000,
    countText: "1100株",
    lat: 39.908,
    lng: 116.457,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "以丁香为重点花卉，适合在春季末段呈现香花植物。"
  },
  {
    id: "guanzhuang-muhly",
    district: "朝阳区",
    place: "官庄公园",
    plant: "粉黛乱子草",
    bloom: "10月至11月中旬",
    months: [10, 11],
    peak: 10,
    area: 631900,
    countText: "7500平米",
    lat: 39.913,
    lng: 116.588,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "秋季观赏草点位，用于扩展春花之外的季节性变化。"
  },
  {
    id: "dongba-ginkgo",
    district: "朝阳区",
    place: "东坝公园",
    plant: "银杏",
    bloom: "10月至11月",
    months: [10, 11],
    peak: 11,
    area: 2342000,
    countText: "10035株/306亩",
    lat: 39.961,
    lng: 116.560,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "秋季叶色植物样本，后续可作为非花类季相图层单独管理。"
  },
  {
    id: "changying-ginkgo",
    district: "朝阳区",
    place: "常营公园",
    plant: "银杏",
    bloom: "10月至12月",
    months: [10, 11, 12],
    peak: 11,
    area: 10654800,
    countText: "11000株/400亩",
    lat: 39.934,
    lng: 116.598,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "秋冬季相点位，适合表现北京植物景观从花到叶色的过渡。"
  },
  {
    id: "yuyuantan-sakura",
    district: "海淀区",
    place: "玉渊潭公园",
    plant: "樱花",
    bloom: "3月下旬至4月下旬",
    months: [3, 4],
    peak: 4,
    area: 500000,
    countText: "近3000株，40余个品种",
    lat: 39.918,
    lng: 116.307,
    source: "北京市园林绿化局 2026年樱花赏花指南",
    description: "北京最负盛名的樱花观赏地，每年举办樱花节，早樱晚樱接力绽放。"
  },
  {
    id: "yihe-peach",
    district: "海淀区",
    place: "颐和园",
    plant: "桃花",
    bloom: "3月中旬至4月中旬",
    months: [3, 4],
    peak: 3,
    area: 80000,
    countText: "西堤山桃及湖岸碧桃",
    lat: 39.992,
    lng: 116.262,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "西堤山桃夹岸，湖光花色相映，是北京春季最具代表性的桃花观赏地之一。"
  },
  {
    id: "yihe-magnolia",
    district: "海淀区",
    place: "颐和园",
    plant: "玉兰",
    bloom: "3月下旬至4月中旬",
    months: [3, 4],
    peak: 4,
    area: 3000,
    countText: "乐寿堂古玉兰及邀月门沿线",
    lat: 39.999,
    lng: 116.273,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "乐寿堂古玉兰为京城著名古树，邀月门至乐寿堂沿线玉兰成景。"
  },
  {
    id: "yihe-lotus",
    district: "海淀区",
    place: "颐和园",
    plant: "荷花",
    bloom: "6月下旬至8月下旬",
    months: [6, 7, 8],
    peak: 7,
    area: 250000,
    countText: "昆明湖大面积荷花",
    lat: 39.995,
    lng: 116.270,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "昆明湖荷花与万寿山佛香阁同框，是北京夏季最经典的荷景之一。"
  },
  {
    id: "temple-of-heaven-violet",
    district: "东城区",
    place: "天坛公园",
    plant: "二月兰",
    bloom: "3月下旬至5月上旬",
    months: [3, 4, 5],
    peak: 4,
    area: 600000,
    countText: "祈年殿西侧大面积野生二月兰花海",
    lat: 39.880,
    lng: 116.404,
    source: "北京市园林绿化局 2026年二月兰赏花指南",
    description: "祈年殿西侧古柏林下二月兰遍野盛开，是北京最壮观的城市花海景观之一。"
  },
  {
    id: "temple-of-heaven-lilac",
    district: "东城区",
    place: "天坛公园",
    plant: "丁香",
    bloom: "4月至5月",
    months: [4, 5],
    peak: 4,
    area: 20000,
    countText: "丁香林，百余株",
    lat: 39.884,
    lng: 116.410,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "天坛丁香林与古柏相映，花时香气弥漫，是中心城区重要的丁香观赏点。"
  },
  {
    id: "beihai-lotus",
    district: "西城区",
    place: "北海公园",
    plant: "荷花",
    bloom: "6月下旬至8月下旬",
    months: [6, 7, 8],
    peak: 7,
    area: 150000,
    countText: "太液池荷花及湖心区水生花卉",
    lat: 39.927,
    lng: 116.386,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "太液池荷花与白塔相映，是北京最经典的皇家园林夏季景观。"
  },
  {
    id: "zizhuyuan-lotus",
    district: "海淀区",
    place: "紫竹院公园",
    plant: "荷花",
    bloom: "6月下旬至8月",
    months: [6, 7, 8],
    peak: 7,
    area: 80000,
    countText: "荷塘面积较大，品种多样",
    lat: 39.944,
    lng: 116.310,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "紫竹院荷花渡是夏日赏荷佳处，荷塘与翠竹相映成趣。"
  },
  {
    id: "taoranting-rose",
    district: "西城区",
    place: "陶然亭公园",
    plant: "月季",
    bloom: "5月至10月",
    months: [5, 6, 7, 8, 9, 10],
    peak: 5,
    area: 30000,
    countText: "月季园，品种丰富",
    lat: 39.868,
    lng: 116.371,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "陶然亭月季园为南城重要月季观赏点，花期内连续开花。"
  },
  {
    id: "taoranting-crabapple",
    district: "西城区",
    place: "陶然亭公园",
    plant: "海棠",
    bloom: "4月",
    months: [4],
    peak: 4,
    area: 15000,
    countText: "海棠园，多种海棠品种",
    lat: 39.869,
    lng: 116.374,
    source: "北京市园林绿化局 2026年海棠赏花指南",
    description: "陶然亭海棠于春日沿湖绽放，与亭台楼阁相映成趣。"
  },
  {
    id: "jingshan-peony",
    district: "西城区",
    place: "景山公园",
    plant: "牡丹",
    bloom: "4月中旬至5月中旬",
    months: [4, 5],
    peak: 4,
    area: 15000,
    countText: "两万余株，500余个品种",
    lat: 39.923,
    lng: 116.397,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "景山牡丹品种和数量居北京前列，万春亭下牡丹与故宫同框。"
  },
  {
    id: "beihai-ginkgo",
    district: "西城区",
    place: "北海公园",
    plant: "银杏",
    bloom: "10月下旬至11月中旬",
    months: [10, 11],
    peak: 11,
    area: 5000,
    countText: "银杏大道及琼岛周边",
    lat: 39.926,
    lng: 116.390,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "北海银杏与红墙绿瓦相衬，秋日金黄满园。"
  },
  {
    id: "xiangshan-ginkgo",
    district: "海淀区",
    place: "香山公园",
    plant: "银杏",
    bloom: "10月下旬至11月中旬",
    months: [10, 11],
    peak: 11,
    area: 10000,
    countText: "古银杏树及红叶林间",
    lat: 39.989,
    lng: 116.182,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "香山古银杏与黄栌红叶交织，秋色层次丰富。"
  },
  {
    id: "yihe-wintersweet",
    district: "海淀区",
    place: "颐和园",
    plant: "蜡梅",
    bloom: "12月下旬至3月",
    months: [12, 1, 2, 3],
    peak: 2,
    area: 2000,
    countText: "乐农轩、畅观堂区域",
    lat: 40.000,
    lng: 116.275,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "乐农轩蜡梅寒冬绽放，是北京冬季寻梅的知名去处。"
  },
  {
    id: "zhongshan-plum",
    district: "东城区",
    place: "中山公园",
    plant: "梅花",
    bloom: "3月上旬至4月上旬",
    months: [3, 4],
    peak: 3,
    area: 3000,
    countText: "梅园，多个品种",
    lat: 39.906,
    lng: 116.393,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "中山公园梅园位于社稷坛南侧，与古柏交相辉映。"
  },
  {
    id: "zhongshan-jasmine",
    district: "东城区",
    place: "中山公园",
    plant: "迎春",
    bloom: "2月下旬至4月上旬",
    months: [2, 3, 4],
    peak: 3,
    area: 500,
    countText: "水榭沿岸及花坛边缘",
    lat: 39.909,
    lng: 116.390,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "中山公园迎春花沿水系分布，是北京城区最早报春的观赏植物之一。"
  },
  {
    id: "temple-of-heaven-forsythia",
    district: "东城区",
    place: "天坛公园",
    plant: "连翘",
    bloom: "3月中旬至4月下旬",
    months: [3, 4],
    peak: 4,
    area: 8000,
    countText: "外坛及步道沿线",
    lat: 39.883,
    lng: 116.405,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "天坛外坛连翘成片开放，金黄灿烂，与古柏相映成趣。"
  },
  {
    id: "national-botanical-almond",
    district: "海淀区",
    place: "国家植物园（北园）",
    plant: "榆叶梅",
    bloom: "3月下旬至4月下旬",
    months: [3, 4, 5],
    peak: 4,
    area: 12000,
    countText: "榆叶梅专类区",
    lat: 39.993,
    lng: 116.207,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "国家植物园榆叶梅品种丰富，粉色花团锦簇，为春季重要观花灌木。"
  },
  {
    id: "national-botanical-peach",
    district: "海淀区",
    place: "国家植物园（北园）",
    plant: "碧桃",
    bloom: "3月下旬至4月下旬",
    months: [3, 4],
    peak: 4,
    area: 30000,
    countText: "碧桃园，数十个品种",
    lat: 39.994,
    lng: 116.204,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "国家植物园碧桃园收集展示大量观赏桃花品种，花开时节灿若云霞。"
  },
  {
    id: "zhongshan-tulip",
    district: "东城区",
    place: "中山公园",
    plant: "郁金香",
    bloom: "4月上旬至5月上旬",
    months: [4, 5],
    peak: 4,
    area: 20000,
    countText: "百余个品种，数十万株",
    lat: 39.907,
    lng: 116.392,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "中山公园郁金香为北京之最，每年举办郁金香花展，品种和数量均居前列。"
  },
  {
    id: "flower-harbor-tulip",
    district: "顺义区",
    place: "北京国际鲜花港",
    plant: "郁金香",
    bloom: "4月上旬至5月中旬",
    months: [4, 5],
    peak: 4,
    area: 100000,
    countText: "大规模郁金香花海",
    lat: 40.137,
    lng: 116.724,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "鲜花港春季郁金香文化节，大面积花海景观，品种繁多。"
  },
  {
    id: "national-botanical-tulip",
    district: "海淀区",
    place: "国家植物园（北园）",
    plant: "郁金香",
    bloom: "4月上旬至5月上旬",
    months: [4, 5],
    peak: 4,
    area: 15000,
    countText: "郁金香专类展区",
    lat: 39.992,
    lng: 116.206,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "国家植物园郁金香展区与桃花、丁香同期，构成春季百花盛景。"
  },
  {
    id: "jingshan-peony-herb",
    district: "西城区",
    place: "景山公园",
    plant: "芍药",
    bloom: "5月上旬至5月下旬",
    months: [5],
    peak: 5,
    area: 8000,
    countText: "品种园，牡丹芍药接力绽放",
    lat: 39.922,
    lng: 116.398,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "景山公园牡丹谢后芍药接力，赏花期可从4月中旬延续至5月底。"
  },
  {
    id: "national-botanical-peony-herb",
    district: "海淀区",
    place: "国家植物园（南园）",
    plant: "芍药",
    bloom: "5月上旬至6月上旬",
    months: [5, 6],
    peak: 5,
    area: 20000,
    countText: "芍药牡丹专类园",
    lat: 39.988,
    lng: 116.203,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "国家植物园南园芍药品种丰富，与牡丹专类园相邻，便于对比观赏。"
  },
  {
    id: "zizhuyuan-wisteria",
    district: "海淀区",
    place: "紫竹院公园",
    plant: "紫藤",
    bloom: "4月中旬至5月上旬",
    months: [4, 5],
    peak: 4,
    area: 2000,
    countText: "紫藤架长廊",
    lat: 39.945,
    lng: 116.312,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "紫竹院紫藤花架沿湖而设，花开时紫云垂挂，清香四溢。"
  },
  {
    id: "aosen-sunflower",
    district: "朝阳区",
    place: "奥林匹克森林公园",
    plant: "向日葵",
    bloom: "7月中旬至8月下旬",
    months: [7, 8],
    peak: 8,
    area: 50000,
    countText: "花田野趣景区，数万株",
    lat: 40.020,
    lng: 116.396,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "奥森北园“花田野趣”景区向日葵花海，是北京夏季最受欢迎的向日葵观赏地。"
  },
  {
    id: "flower-harbor-sunflower",
    district: "顺义区",
    place: "北京国际鲜花港",
    plant: "向日葵",
    bloom: "7月至9月",
    months: [7, 8, 9],
    peak: 8,
    area: 40000,
    countText: "秋季花展向日葵片区",
    lat: 40.136,
    lng: 116.726,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "鲜花港秋季向日葵花田，与菊花、观赏草共同构成秋日缤纷景观。"
  },
  {
    id: "beihai-chrysanthemum",
    district: "西城区",
    place: "北海公园",
    plant: "菊花",
    bloom: "9月下旬至11月中旬",
    months: [9, 10, 11],
    peak: 10,
    area: 5000,
    countText: "菊花展，数百个品种",
    lat: 39.924,
    lng: 116.388,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "北海公园每年举办菊花展，为北京秋日传统花事活动。"
  },
  {
    id: "flower-harbor-chrysanthemum",
    district: "顺义区",
    place: "北京国际鲜花港",
    plant: "菊花",
    bloom: "9月中旬至10月下旬",
    months: [9, 10],
    peak: 10,
    area: 60000,
    countText: "秋季菊花展",
    lat: 40.135,
    lng: 116.720,
    source: "北京市园林绿化局 2026年春季全市公园赏花片区",
    description: "鲜花港秋季菊花文化节，大面积菊花花海，品种丰富。"
  }
];
